#!/usr/bin/sh
cd "/opt/dingtalk/$(cat /opt/dingtalk/version)"
export QT_IM_MODULE=fcitx
export QT_QPA_PLATFORM="wayland;xcb"
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_PLUGIN_PATH="$(pwd)"
LD_PRELOAD="./plugins/dtwebview/libcef.so" ./com.alibabainc.dingtalk $1
