#!/usr/bin/sh
set -e

# wechat only support xcb
export QT_QPA_PLATFORM="xcb"
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# remove the single-account login restriction
rm -f "$HOME/.xwechat/lock/lock.ini"

/opt/wechat/wechat "$@"
